### ISSUE TITLE
Latest awx-ee image  doesn't seem to want to start?

### ISSUE THREAD

**Issue by liquidspikes** [ansible/awx-ee#101]
Hello,

I have been playing a bit with awx-operator (0.16.1) and awx-web (19.5.1) and recently went through the process of deleting my pods and pulling the awx-ee:latest image (which appears was updated about 8 hours ago, manifest: ba162e341631).

Unfortunately, I get the following error when the awx-ee container attempts to start:

```
kubectl logs awx-7c7f97bf75-dpq4t -c awx-ee -n awx
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        /root/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:20 +0x132
```

This causes the AWX pod to fail in a CrashLoop BackOff State.

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Created    36m                  kubelet            Created container awx-task
  Normal   Started    36m                  kubelet            Started container awx-task
  Normal   Created    36m                  kubelet            Created container awx-web
  Normal   Pulling    36m (x2 over 36m)    kubelet            Pulling image "quay.io/ansible/awx-ee:latest"
  Normal   Created    36m (x2 over 36m)    kubelet            Created container awx-ee
  Normal   Started    36m (x2 over 36m)    kubelet            Started container awx-ee
  Normal   Pulled     36m                  kubelet            Successfully pulled image "quay.io/ansible/awx-ee:latest" in 315.368081ms
  Warning  BackOff    60s (x162 over 36m)  kubelet            Back-off restarting failed container`

```

```
kubectl get pods -n awx
NAME                                               READY   STATUS             RESTARTS         AGE
awx-operator-controller-manager-6c96d9b446-tczbn   2/2     Running            4 (102m ago)     24h
awx-7c7f97bf75-dpq4t                            3/4     CrashLoopBackOff   23 (3m42s ago)   97m
```

I am running a bare-metal Kubernetes cluster on Ubuntu 20.04 LTS.
 
Please let me know if there is anything else I can do to assist. :)

Thanks! :)

**Comment by liquidspikes** [comment]
I modified the pod spec to point to the previous awx-ee:0.6.0 image and it seems to work great. 
I believe the latest image just got hosed! Bad upload?

**Comment by garyhodgson** [comment]
I'm seeing the same problem, and in case others have the same difficulty as I did, it is the "control_plane_ee_image" spec param that has to be explicitly given, not the one under ee_images, e.g. 
 
```
spec:
  image_pull_policy: Always
  control_plane_ee_image: quay.io/ansible/awx-ee:0.6.0
  ee_images:
    - name: my-awx-ee
      image: ...
```

**Comment by markstoel** [comment]
@garyhodgson , @liquidspikes  Which version of the operator are you using? Because with the latest version and awx-ee:0.6.0 it will not start any job pods..

**Comment by garyhodgson** [comment]
@markstoel quay.io/ansible/awx-operator:0.16.1 - but I only got to the stage of starting AWX - I haven't yet attempted to start a job.  Once I do I will reply here.

**Comment by garyhodgson** [comment]
@markstoel I believe I am seeing the same problem. the Source Control Update Job is hanging with status Pending, and no job pod is started.

**Comment by mario-oberwalder** [comment]
I believe we have the same problem on Openshift 4.8.22

**Comment by kdelee** [comment]
Looks like it is busted because of receptor
`podman run --rm quay.io/ansible/awx-ee:latest receptor --version`
```
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        /root/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:20 +0x132
```

People need to pin to 0.6.0 until receptor is fixed...going over there to see whats up

**Comment by AlanCoding** [comment]
I believe we may be seeing the same problem with AAP controller VM installs running container group jobs. Watching this.

**Comment by shanemcd** [comment]
New image has been pushed up which will hopefully stop the bleeding. Will wait for folks to confirm before closing this.

**Comment by chofstede** [comment]
New version does not start at all. Error in Kubernetes:

Error: cannot find volume "awx-receptor-config" to mount into container "awx-ee"

**Comment by kdelee** [comment]
@chofstede its working for me with this as my awx CR
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-prod
  namespace: awx
spec:
  admin_email: admin@localhost
  admin_user: admin
  create_preload_data: true
  garbage_collect_secrets: false
  image: quay.io/ansible/awx
  image_pull_policy: Always
  image_version: latest
  loadbalancer_port: 80
  loadbalancer_protocol: http
  nodeport_port: 30080
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  service_type: nodeport
  task_privileged: false
```

that was a fresh deployment. My previous deployment that had been crash looping on trying to start the awx-ee fixed itself w/o restarting the pod because it pulled the new `:latest` tag and the container was able to start
